services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    container_name: recetas-backend
    env_file:
      - ./recetas.env
    expose:
      - "8080"
    networks:
      - recetas-network
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/nginx/Dockerfile
    container_name: recetas-frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - recetas-network
    volumes:
      - ./frontend/certbot/conf:/etc/letsencrypt
      - ./frontend/certbot/www:/var/www/certbot
      - ./frontend/nginx/conf:/etc/nginx/conf.d:ro
      - ./frontend/nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    command: "/bin/sh -c 'while :; do sleep 12h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: recetas-certbot
    volumes:
      - ./frontend/certbot/conf:/etc/letsencrypt
      - ./frontend/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=https://rincon-sabores.online/prometheus/'
      - '--web.route-prefix=/prometheus'
    expose:
      - "9090"
    networks:
      - recetas-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    env_file:
      - ./recetas.env
    environment:
      GF_SERVER_ROOT_URL: https://rincon-sabores.online/grafana/
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana-data:/var/lib/grafana
    expose:
      - "3000"
    depends_on:
      - prometheus
    networks:
      - recetas-network
    restart: unless-stopped

networks:
  recetas-network:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:
