spring.datasource.url=jdbc:mysql://localhost:3306/RecetasApp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=recetas_user
spring.datasource.password=RecetasApp123